id: P4161A13E
initial_creation_type: ocr
source_metadata:
  volumes:
    0354c01dead24dc4a3176df2aa005cd2:
      base_file: v089.txt
      image_group_id: I1PD95934
      title: འདུལ་བའི་མདོའི་འགྲེལ་པ་མངོན་པར་བརྗོད་པ་རང་གི་རྣམ་པར་བཤད་པ།
      total_pages: 1540
      volume_number: 89
vol2fn:
  v089: v089.txt
