id: P4161A13E
initial_creation_type: ocr
source_metadata:
  volumes:
    0be90671fa2747e186f38ac5c39ef665:
      base_file: v089.txt
      image_group_id: I1PD95934
      title: འདུལ་བའི་མདོའི་འགྲེལ་པ་མངོན་པར་བརྗོད་པ་རང་གི་རྣམ་པར་བཤད་པ།
      total_pages: 1540
      volume_number: 89
